In [2]:
print('17. 参数初始化')

17. 参数初始化


In [3]:
import numpy as np
import torch
from torch import nn


In [4]:
net1 = nn.Sequential(
    nn.Linear(30,40),
    nn.ReLU(),
    nn.Linear(40,50),
    nn.ReLU(),
    nn.Linear(50,10)
)

In [5]:
w1 = net1[0].weight
b1 = net1[0].bias
print(w1)

Parameter containing:
tensor([[ 0.1393,  0.0342, -0.1013,  ..., -0.0659, -0.1605, -0.1082],
        [ 0.0688,  0.1410,  0.0753,  ..., -0.1194, -0.0361,  0.0570],
        [-0.0370, -0.0980, -0.1168,  ..., -0.0629,  0.1133, -0.1317],
        ...,
        [ 0.0582,  0.1643, -0.1362,  ..., -0.0303, -0.0705,  0.0248],
        [-0.0337,  0.1442, -0.0691,  ...,  0.0006,  0.0549,  0.0117],
        [ 0.0756, -0.0278, -0.0100,  ...,  0.0618,  0.0627, -0.0785]],
       requires_grad=True)


In [6]:
net1[0].weight.data = torch.from_numpy(np.random.uniform(3,5,size=(40,30)))
print(net1[0].weight)

Parameter containing:
tensor([[4.7950, 4.6385, 4.2758,  ..., 3.2682, 4.6645, 3.7130],
        [4.9174, 4.9571, 3.4524,  ..., 4.2832, 4.3980, 4.3547],
        [3.0903, 3.6660, 4.3986,  ..., 4.5817, 4.7823, 4.9164],
        ...,
        [3.7550, 3.2415, 4.5328,  ..., 4.8928, 3.2219, 3.3716],
        [3.3365, 4.4923, 4.5034,  ..., 3.8579, 4.5991, 3.3664],
        [4.0578, 4.8959, 4.7040,  ..., 4.0524, 3.8360, 4.9499]],
       dtype=torch.float64, requires_grad=True)


In [10]:

for layer in net1:
    if isinstance(layer, nn.Linear):
        param_shape = layer.weight.shape
        n_in = layer.in_features
        n_out = layer.out_features
        layer.weight.data = torch.from_numpy(
            np.random.normal(-np.sqrt(6.0/(n_in+n_out)), 
                             np.sqrt(6.0/(n_in+n_out)), 
                             size=param_shape))

In [11]:


class sim_net(nn.Module):
    def __init__(self):
        super(sim_net, self).__init__()
        self.l1 = nn.Sequential(
            nn.Linear(30,40),
            nn.ReLU()
        )
        self.l1[0].weight.data = torch.randn(40,30)
        
        self.l2 = nn.Sequential(
            nn.Linear(40,50),
            nn.ReLU()
        )
        
        self.l3 = nn.Sequential(
            nn.Linear(50,10),
            nn.ReLU()
        )
    
    def forward(self, x):
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        return x
    
    

In [12]:
net2 = sim_net()
for i in net2.children():
    print(i)
    

Sequential(
  (0): Linear(in_features=30, out_features=40, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Linear(in_features=40, out_features=50, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Linear(in_features=50, out_features=10, bias=True)
  (1): ReLU()
)


In [13]:
for i in net2.modules():
    print(i)

sim_net(
  (l1): Sequential(
    (0): Linear(in_features=30, out_features=40, bias=True)
    (1): ReLU()
  )
  (l2): Sequential(
    (0): Linear(in_features=40, out_features=50, bias=True)
    (1): ReLU()
  )
  (l3): Sequential(
    (0): Linear(in_features=50, out_features=10, bias=True)
    (1): ReLU()
  )
)
Sequential(
  (0): Linear(in_features=30, out_features=40, bias=True)
  (1): ReLU()
)
Linear(in_features=30, out_features=40, bias=True)
ReLU()
Sequential(
  (0): Linear(in_features=40, out_features=50, bias=True)
  (1): ReLU()
)
Linear(in_features=40, out_features=50, bias=True)
ReLU()
Sequential(
  (0): Linear(in_features=50, out_features=10, bias=True)
  (1): ReLU()
)
Linear(in_features=50, out_features=10, bias=True)
ReLU()


In [14]:

for layer in net2.modules():
    if isinstance(layer, nn.Linear):
        param_shape = layer.weight.shape
        layer.weight.data = torch.from_numpy(np.random.normal(0,0.5,size=param_shape))
        

In [16]:
for layer in net2.modules():
    if isinstance(layer, nn.Linear):
        print(layer.in_features)
        print(layer.out_features)
        print(layer.weight.data)

30
40
tensor([[ 0.0670,  0.5856,  0.9814,  ...,  0.7756, -1.0845, -0.0565],
        [-0.0133,  0.0352,  0.0382,  ..., -0.6595,  0.5797, -0.8109],
        [ 0.4446,  0.7263,  0.1032,  ..., -0.1998, -0.3925, -0.3667],
        ...,
        [ 0.3232,  0.1433, -0.4798,  ...,  0.5533, -0.3939, -0.4786],
        [ 0.5342, -0.5778,  0.4263,  ..., -0.1004,  0.2145, -0.3758],
        [ 0.0881, -0.7196, -0.2196,  ...,  0.4783,  0.1176,  0.9371]],
       dtype=torch.float64)
40
50
tensor([[ 0.0145, -0.6655, -1.1905,  ...,  0.2446,  0.4366, -0.2178],
        [ 1.0316,  0.4082,  0.0238,  ...,  0.1800,  0.2315,  0.9798],
        [ 0.0129, -0.9935, -0.2897,  ...,  0.4993,  0.5429, -0.2808],
        ...,
        [-0.1920,  0.3836,  0.0366,  ...,  0.8285,  0.1429,  0.9746],
        [-0.2358, -0.2187, -0.5549,  ...,  0.3022, -0.0873, -0.5389],
        [-0.9649,  0.3745,  0.6522,  ...,  0.5665,  0.3041, -0.1081]],
       dtype=torch.float64)
50
10
tensor([[-1.3472e-01,  3.9765e-01, -4.0193e-01,  5.8640e-0

In [17]:
# torch.nn.init
from torch.nn import init
print(net1[0].weight)


Parameter containing:
tensor([[-0.2094,  0.0319, -0.7622,  ..., -0.4885, -0.0992, -0.8959],
        [-0.2159,  0.0797, -0.6359,  ..., -0.0237, -0.8760, -0.2513],
        [-0.4455, -0.3976, -0.8292,  ..., -0.0503, -0.7132, -0.5125],
        ...,
        [ 0.1304,  0.1706, -0.6587,  ..., -0.5973,  0.2466, -0.6278],
        [-0.3608, -0.3688, -0.2169,  ..., -0.0129,  0.0074,  0.0656],
        [-0.3450, -0.0887, -0.3951,  ..., -0.2964, -0.0080, -0.0558]],
       dtype=torch.float64, requires_grad=True)


In [19]:
init.xavier_uniform_(net1[0].weight)


Parameter containing:
tensor([[-0.2167,  0.1717,  0.1476,  ..., -0.1428,  0.1155,  0.1211],
        [ 0.2419, -0.0752, -0.0981,  ..., -0.0314, -0.0269,  0.2063],
        [ 0.2284,  0.0365, -0.0352,  ...,  0.1686, -0.2181,  0.1994],
        ...,
        [-0.1991, -0.1123,  0.0811,  ...,  0.0517, -0.1563, -0.0650],
        [ 0.1344, -0.1792, -0.0573,  ..., -0.0122, -0.2517, -0.1374],
        [-0.1347, -0.0834,  0.0874,  ..., -0.1921, -0.0532, -0.0180]],
       dtype=torch.float64, requires_grad=True)