In [1]:

print("torch autograd!")

torch autograd!


In [2]:

import torch


In [3]:
x = torch.ones(2,2,requires_grad= True)
print(x)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
print(x.type())


torch.FloatTensor


In [5]:
y = x + 2
print(y)


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
print(y.grad_fn)


In [7]:
z = y*y*3
out = z.mean()
print(z)
print(out)


tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [10]:
a = torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)


False
True


In [11]:
print(a*a)


tensor([[ 2.7594, 19.4195],
        [ 0.1811,  2.4943]], grad_fn=<MulBackward0>)


In [12]:
c = torch.ones([2,2])
d = torch.ones([2,2])
print(c*d)


tensor([[1., 1.],
        [1., 1.]])


In [13]:
print(c**d)


tensor([[1., 1.],
        [1., 1.]])


In [14]:
print(c.mm(d))


tensor([[2., 2.],
        [2., 2.]])


In [15]:
print(x)
print(out)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor(27., grad_fn=<MeanBackward0>)


In [16]:
print(x.grad)


None


In [17]:
out.backward()
print(x.grad)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [18]:
x = torch.randn(3, requires_grad=True)
y = x*2
while y.data.norm()<1000:
    y = y*2

print(y)


tensor([ -687.0881,   -24.3363, -1423.5774], grad_fn=<MulBackward0>)


In [19]:
v = torch.tensor([0.1,1.0,0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)


tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [20]:
print(x.requires_grad)


True


In [21]:
print((x**2).requires_grad)


True


In [22]:
with torch.no_grad():
    print((x**2).requires_grad)
    


False


In [23]:
x = torch.randn(5,5)
print(x)


tensor([[ 0.7164, -1.2912, -0.0445,  1.1666, -0.9610],
        [ 0.7600,  0.0137,  2.6942,  0.2081, -1.5551],
        [ 0.6873, -0.6588,  0.0640, -0.4495, -0.3914],
        [ 0.6051,  0.9310, -0.9787,  1.1055,  0.4330],
        [ 0.9965,  1.2747,  1.1911,  1.3598, -0.3441]])


In [24]:
print(x.requires_grad)


False


In [26]:
y = torch.randn(5,5)
print(y.requires_grad)
z = torch.randn((5,5), requires_grad=True)
print(z.requires_grad)


False
True


In [27]:
a = x+y
print(a.requires_grad)
b = a+z
print(b.requires_grad)


False
True
