In [ ]:
print("Hello World!")

In [4]:
from __future__ import print_function
import torch
print('Hello Torch')

ModuleNotFoundError: No module named 'torch'

In [3]:
x = torch.empty(5,3)
print(x)


NameError: name 'torch' is not defined

In [3]:
x  = torch.rand(5,3)
print(x)

tensor([[0.4273, 0.9370, 0.9686],
        [0.1202, 0.2431, 0.8533],
        [0.3873, 0.9353, 0.8676],
        [0.6246, 0.0640, 0.7636],
        [0.4758, 0.9056, 0.5944]])


In [4]:
x = torch.zeros(5,3,dtype=torch.long)

In [5]:
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
print(x)


tensor([[ 1.1649,  1.7106, -0.4891],
        [-1.6466,  1.3510, -0.6150],
        [-0.2037,  0.4017,  0.5861],
        [ 0.0853, -0.0527,  0.0289],
        [ 0.6582, -1.1267,  0.6925]])


In [9]:
x.type()


'torch.FloatTensor'

In [10]:
x.dtype

torch.float32

In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
x.size().__len__()

2

In [13]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 1.5006,  2.5630,  0.4387],
        [-1.6130,  2.0569, -0.2212],
        [ 0.7456,  0.9642,  0.9883],
        [ 0.4346,  0.3336,  0.9916],
        [ 1.3803, -0.8654,  1.3251]])


In [14]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)

In [16]:
print(x)
print(x.item())

tensor([-0.5693])
-0.5692745447158813
